package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *MessageQueueConfig) DeepCopyInto(out *MessageQueueConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessageQueueConfig.
func (in *MessageQueueConfig) DeepCopy() *MessageQueueConfig {
	if in == nil {
		return nil
	}
	out := new(MessageQueueConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *StatefulMigrationSpec) DeepCopyInto(out *StatefulMigrationSpec) {
	*out = *in
	in.MessageQueueConfig.DeepCopyInto(&out.MessageQueueConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulMigrationSpec.
func (in *StatefulMigrationSpec) DeepCopy() *StatefulMigrationSpec {
	if in == nil {
		return nil
	}
	out := new(StatefulMigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *StatefulMigrationStatus) DeepCopyInto(out *StatefulMigrationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.PhaseTimings != nil {
		in, out := &in.PhaseTimings, &out.PhaseTimings
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SourcePodLabels != nil {
		in, out := &in.SourcePodLabels, &out.SourcePodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SourceContainers != nil {
		in, out := &in.SourceContainers, &out.SourceContainers
		*out = make([]corev1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulMigrationStatus.
func (in *StatefulMigrationStatus) DeepCopy() *StatefulMigrationStatus {
	if in == nil {
		return nil
	}
	out := new(StatefulMigrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *StatefulMigration) DeepCopyInto(out *StatefulMigration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulMigration.
func (in *StatefulMigration) DeepCopy() *StatefulMigration {
	if in == nil {
		return nil
	}
	out := new(StatefulMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StatefulMigration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *StatefulMigrationList) DeepCopyInto(out *StatefulMigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StatefulMigration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulMigrationList.
func (in *StatefulMigrationList) DeepCopy() *StatefulMigrationList {
	if in == nil {
		return nil
	}
	out := new(StatefulMigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StatefulMigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
